RoleMenuWeb/Controllers/MenuRoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RoleMenuWeb.Models;
using RoleMenuWeb.Services;
using RoleMenuWeb.ViewModel;
using System.Linq;

namespace RoleMenuWeb.Controllers
{
    [Authorize]
    [AuthorizeAccess]
    public class MenuRoleController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IDataAccessService _dataAccessService;
        private readonly ILogger<MenuRoleController> _logger;
        public MenuRoleController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager, IDataAccessService dataAccessService, ILogger<MenuRoleController> logger)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _dataAccessService = dataAccessService;
            _logger = logger;
        }
        [HttpGet]
        public async Task<IActionResult> Roles()        
        {
            var roleViewModel = new List<RoleViewModel>();
            try
            {
                var roles = await _roleManager.Roles.ToListAsync();
                foreach (var item in roles)
                {
                    if(item.Name != "SuperAdmin")
                    {
                        roleViewModel.Add(new RoleViewModel()
                        {
                            Id = item.Id,
                            Name = item.Name,
                        });
                    }                   
                }
            }
            catch (Exception ex)
            {
                _logger?.LogError(ex, ex.GetBaseException().Message);
            }
            return View(roleViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> CreateRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(RoleViewModel viewModel)
        {
            if (viewModel.Name != null)
            {
                var result = await _roleManager.CreateAsync(new IdentityRole() { Name = viewModel.Name });
                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(Roles));
                }
                else
                {
                    ModelState.AddModelError("Name", string.Join(",", result.Errors));
                }
            }

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Users()
        {
            var userViewModel = new List<UserViewModel>();

            try
            {
                var users = await _userManager.Users.ToListAsync();
                foreach (var item in users)
                {
                    if(item.UserName != "superadmin@gmail.com")
                    {
                        userViewModel.Add(new UserViewModel()
                        {
                            Id = item.Id,
                            Email = item.Email,
                            UserName = item.UserName,
                        });
                    }
                    
                }
            }
            catch (Exception ex)
            {
                _logger?.LogError(ex, ex.GetBaseException().Message);
            }

            return View(userViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            var viewModel = new UserViewModel();
            if (!string.IsNullOrWhiteSpace(id))
            {
                var user = await _userManager.FindByIdAsync(id);
                var userRoles = await _userManager.GetRolesAsync(user);
                viewModel.Email = user?.Email;
                viewModel.UserName = user?.UserName;

                var allRoles = await _roleManager.Roles.ToListAsync();
                viewModel.Roles = allRoles.Select(x => new RoleViewModel()
                {
                    Id = x.Id,
                    Name = x.Name,
                    Selected = userRoles.Contains(x.Name)
                }).ToArray();

            }

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditUser(UserViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(viewModel.Id);
                var userRoles = await _userManager.GetRolesAsync(user);

                await _userManager.RemoveFromRolesAsync(user, userRoles);
                await _userManager.AddToRolesAsync(user, viewModel.Roles.Where(x => x.Selected).Select(x => x.Name));

                return RedirectToAction(nameof(Users));
            }

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> EditRolePermission(string id)
        {
            var permissions = new List<NavigationMenuViewModel>();
            if (!string.IsNullOrWhiteSpace(id))
            {
                permissions = await _dataAccessService.GetPermissionsByRoleIdAsync(id);
            }
            ViewData["Role"] = _roleManager.FindByIdAsync(id).Result.Name;
            return View(permissions);
        }

        [HttpPost]
        public async Task<IActionResult> EditRolePermission(string id, List<NavigationMenuViewModel> viewModel)
        {

            var permissionIds = viewModel.Where(x => x.Permitted).Select(x => x.Id);
            await _dataAccessService.SetPermissionsByRoleIdAsync(id, permissionIds);
            return RedirectToAction(nameof(Roles));

        }

        [HttpGet]
        public IActionResult Methods()
        {
            var ControllerMethod = _dataAccessService.LoadMethods();
            return View(ControllerMethod);
        }

        [HttpPost]
        public IActionResult Methods(List<NavigationMenuViewModel> viewModel)
        {
            var ControllerMethod = _dataAccessService.LoadMethods();
            foreach (var VM in ControllerMethod)
            {
                if (!VM.Permitted)
                {
                    var menus = new NavigationMenu
                    {
                        Name = VM.Name,
                        ActionName = VM.ActionName,
                        ControllerName = VM.ControllerName,
                        ParentMenuId = VM.ParentMenuId,
                    };
                    _dataAccessService.AddMenu(menus);
                }               
            }
            
            return RedirectToAction("Methods");
        }
        public IActionResult Test()
        {
            return View();
        }

        public IActionResult Test2()
        {
            return View();
        }

        [AllowAnonymous]
        public IActionResult Demo()
        {
            return View();
        }
    }
}

RoleMenuWeb/Views/MenuRole/CreateRole.cshtml
@model RoleMenuWeb.ViewModel.RoleViewModel
@{
    ViewData["Title"] = "Create Role";
}

<h2>Create Role</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateRole">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group pt-2">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Roles">Back to List</a>
</div>

RoleMenuWeb/Views/MenuRole/Demo.cshtml
@{
    ViewBag.Title = "AllowAnonymous Demo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AllowAnonymous Demo page</h2>
<div class="alert alert-success">
    <h3> You have enough permission.</h3>
</div>

RoleMenuWeb/Views/MenuRole/EditRolePermission.cshtml
@model List<RoleMenuWeb.ViewModel.NavigationMenuViewModel>
@{
    ViewData["Title"] = "Edit Role Permission";
}
<h2>Edit @ViewData["Role"] Role Permission</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditRolePermission">
            <div class="form-group">
                <ul style="list-style-type: none;">
                    @for (var i = 0; i < Model.Count; i++)
                    {
                        <li>
                            <input type="checkbox" asp-for="@Model[i].Permitted" />
                            <label style="margin-left:10px;" asp-for="@Model[i].Permitted">@Model[i].Name</label>
                            <input type="hidden" asp-for="@Model[i].Id" />
                            <input type="hidden" asp-for="@Model[i].Name" />
                        </li>
                    }
                </ul>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="Roles">Back to List</a>
            </div>
        </form>
    </div>
</div>

RoleMenuWeb/Views/MenuRole/EditUser.cshtml
@model RoleMenuWeb.ViewModel.UserViewModel

@{
	ViewData["Title"] = "Edit User";
}

<h1>Edit User</h1>

<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="EditUser">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<input type="hidden" asp-for="Id" class="form-control" />
			<div class="form-group">
				<label asp-for="UserName" class="control-label"></label>
				<input asp-for="UserName" class="form-control" />
				<span asp-validation-for="UserName" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Email" class="control-label"></label>
				<input asp-for="Email" class="form-control" />
				<span asp-validation-for="Email" class="text-danger"></span>
			</div>
			<br/>
			<p>Roles:</p>
			<div class="form-group">
				<ul style="list-style-type: none;">
					@for (var i = 0; i < Model.Roles.Length; i++)
					{
						<li>
							<input type="checkbox" asp-for="@Model.Roles[i].Selected" />
							<label style="margin-left:10px;" asp-for="@Model.Roles[i].Selected">@Model.Roles[i].Name</label>
							<input type="hidden" asp-for="@Model.Roles[i].Id" />
							<input type="hidden" asp-for="@Model.Roles[i].Name" />
						</li>
					}
				</ul>
			</div>
			<div class="form-group">
				<input type="submit" value="Save" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Users">Back to List</a>
</div>

RoleMenuWeb/Views/MenuRole/Methods.cshtml
@model List<RoleMenuWeb.ViewModel.NavigationMenuViewModel>

<h4 class="pb-3">Add Method to Menu List</h4>
<form method="post" action="@Url.Action("Methods", "MenuRole")">
    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th>sl</th>
                <th>Controller Name</th>
                <th>Action Name</th>
                <th>Is Added</th>
            </tr>
        </thead>
        <tbody>
            @{
                int i = 1;
            }
            @foreach (var item in Model)
            {
                <tr>
                    <td>@i</td>
                    <td>@item.ControllerName</td>
                    <td>@item.ActionName</td>
                    <td>@(item.Permitted == true ? "Yes":"No")</td>
                </tr>
                i++;
            }
        </tbody>
    </table>
    <button type="submit" class="btn btn-primary">Save All</button>
</form>

RoleMenuWeb/Views/MenuRole/Roles.cshtml
@model List<RoleMenuWeb.ViewModel.RoleViewModel>
@{
    ViewData["Title"] = "Roles";
}

<div class="row pb-4">
    <div class="col-6">
        <h4>Roles</h4>
    </div>
    <div class="col-6 text-end">
        <a asp-action="CreateRole" asp-controller="MenuRole" class="btn btn-primary">Create Role</a>
    </div>
</div>


<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Id)</td>
                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                <td><a asp-action="EditRolePermission" asp-controller="MenuRole" asp-route-id="@item.Id">Edit Permissions</a></td>
            </tr>
        }
    </tbody>
</table>

RoleMenuWeb/Views/MenuRole/Users.cshtml
@model List<RoleMenuWeb.ViewModel.UserViewModel>

@{
   	ViewData["Title"] = "Users";
 }
    
    <h1>Users</h1>
    <table class="table">
    	<thead>
    		<tr>
  			<th>
  				User Name
  			</th>
  			<th>
   				Email
 			</th>
   			<th>
                Action
   			</th>
   		</tr>
  	</thead>
   	<tbody>
   		@foreach (var item in Model)
  		{
   			<tr>
  				<td>
  					@Html.DisplayFor(modelItem => item.UserName)
   				</td>
   				<td>
   					@Html.DisplayFor(modelItem => item.Email)
  				</td>
   				<td>
 					<a asp-action="EditUser" asp-controller="MenuRole" asp-route-id="@item.Id">Edit</a>
   				</td>
   			</tr>
   		}
   	</tbody>
   </table>